# Notify Springfield that l10n files have updated, by pinging Springfield's Fluent-files
# update pipeline at mozmeao/springfield-fluent-update

name: Ping mozmeao/springfield-fluent-update when main changes
on:
  push:
    branches:
      - main
  workflow_dispatch: # For manual runs, if needed

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  notify-of-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger webhook
        shell: bash
        run: >
          curl -X POST
          https://api.github.com/repos/mozmeao/springfield-fluent-update/actions/workflows/run-fluent-updates.yml/dispatches
          --header "Accept: application/vnd.github+json"
          --header "Authorization: Bearer ${{ secrets.SPRINGFIELD_FLUENT_UPDATE_PAT }}"
          --header "Content-Type: application/json"
          -d '{"ref":"main"}'
        # 'main' as the ref above refers to the branch on the www-fluent-update repo
